[package]
name = "rust-note-api"
version = "0.1.0"
edition = "2021"

[dependencies]
actix = "0.13.5"
actix-web = "4.8.0"
chrono = "0.4.38"
dotenv = "0.15.0"
lazy_static = "1.5.0"
serde = "1.0.204"
serde_json = "1.0.121"
