// Generated by diesel_ext

#![allow(unused)]
#![allow(clippy::all)]

use chrono::{DateTime, Utc};
use diesel::Queryable;
use serde::Serialize;

#[derive(Queryable, Debug, Serialize)]
pub struct Note {
    pub id: i32,
    pub title: String,
    pub content: String,
    pub active: Option<bool>,
    pub created_by: i32,
    pub created_on: Option<DateTime<Utc>>,
    pub updated_on: Option<DateTime<Utc>>,
}

#[derive(Queryable, Debug, Serialize)]
pub struct User {
    pub id: i32,
    pub username: String,
    pub email: String,
    #[serde(skip_serializing)]
    pub password: String,
    pub opt_verified: Option<bool>,
    pub opt_enabled: Option<bool>,
    pub opt_base32: Option<String>,
    pub opt_auth_url: Option<String>,
    pub role: String,
}
